# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'This is my dev collection.'
baseurl:             '/lanyon/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:       
  url:              
  email:           

# Gems
plugins:
  - jekyll-paginate
